server:
  port: 8080
debug: true
mybatis:
  type-aliases-package: com.demo.entity
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root